# True color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Layout from Catppuccin but using terminal defaults
set -g status "on"
set -g status-position bottom
set -g status-justify left
set -g status-left-length "120"
set -g status-right-length "120"

set -g status-left "#[fg=default,bg=default] #S #[fg=default,bg=default,nobold,noitalics,nounderl]"
set -g status-right "#{prefix_highlight} #[fg=default,bg=default] %R  %m/%d"

setw -g window-status-activity-style "fg=default,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "fg=default,bg=default"

setw -g window-status-current-format "#[fg=default,bg=default,nobold,noitalics,nounderl]#[fg=default,bg=default] #I #[fg=default,bg=default,bold] #W #[fg=default,bg=default,nobold,noitalics,nounderl]"
setw -g window-status-format "#[fg=default,bg=default,noitalics] #i #[fg=default,bg=default]#{?#{==:#W,zsh}, ,#{?#{==:#W,nvim}, ,#W }}"

# Window modes
setw -g mode-style "fg=default,bg=default"

# Panes
set -g pane-active-border-style "fg=default,bg=default"
set -g pane-border-style "fg=default,bg=default"

# Messages
set -g message-style "fg=default,bg=default"
set -g message-command-style "fg=default,bg=default"

# Prefix highlight (optional, remove if you don't want it)
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=default,bg=default'

# Mouse
set -g mouse on

# Scroll history
set -g history-limit 10240 

# Snappier escape timing 
set -s escape-time 50
